package rules;

import com.ftn.sbnz.model.Flight;
import com.ftn.sbnz.model.WeatherReport;
import com.ftn.sbnz.model.Runway;
import com.ftn.sbnz.model.facts.*;

rule "Meteo - Tailwind Component"
salience 500
when
    $f : Flight($fn : flightNumber)
    WeatherReport(tailwind > 19)
then
    TailwindDetected factDr = new TailwindDetected();
    factDr.setFlightNumber($fn);
    insert(factDr); 
end

rule "Meteo - Zero Visibility"
salience 500
when
    $f : Flight($fn : flightNumber)
    WeatherReport(visibility < 75)
then
    ZeroVisibility factDr = new ZeroVisibility();
    factDr.setFlightNumber($fn);
    insert(factDr);
    
    TakeoffForbidden tf = new TakeoffForbidden();
    tf.setFlightNumber($fn);
    insert(tf);
end

rule "Meteo - Frost Risk"
salience 500
when
    $f : Flight($fn : flightNumber)
    WeatherReport(temperature <= 0, dewPoint >= temperature) 
then
    FrostRisk factDr = new FrostRisk();
    factDr.setFlightNumber($fn);
    insert(factDr);
    
    SurfacesContaminated sc = new SurfacesContaminated();
    sc.setFlightNumber($fn);
    insert(sc);
end

rule "Infrastructure - Runway Critical State"
salience 500
when
    $f : Flight($fn : flightNumber)
    Runway(rwycc <= 1)
then
    RunwayCritical factDr = new RunwayCritical();
    factDr.setFlightNumber($fn);
    insert(factDr);
    
    RunwayProblem rp = new RunwayProblem();
    rp.setFlightNumber($fn);
    insert(rp);
end

rule "Infrastructure - Runway Risky"
salience 500
when
    $f : Flight($fn : flightNumber)
    Runway(deicingComplete == false || (rwycc > 1 && rwycc <= 3)) 
then
    RunwayRisky factDr = new RunwayRisky();
    factDr.setFlightNumber($fn);
    insert(factDr);
    
    RunwayDifficult rd = new RunwayDifficult();
    rd.setFlightNumber($fn);
    insert(rd);
end