package rules;

import com.ftn.sbnz.model.Flight;
import com.ftn.sbnz.model.facts.*;

// Sva pravila za agregaciju činjenica imaju salience 500

rule "Aggregation - Runway Problem due to difficult runway and snow or ice"
salience 500
when
    $f : Flight($fn : flightNumber)
    RunwayDifficult(flightNumber == $fn)
    SurfacesContaminated(flightNumber == $fn)
then
    // Kada imamo kombinaciju mraza i lošije piste, to je operativni problem (za DELAY)
end

rule "Aggregation - Runway Problem due to difficult runway and strong tailwind"
salience 500
when
    $f : Flight($fn : flightNumber)
    RunwayDifficult(flightNumber == $fn)
    TailwindDetected(flightNumber == $fn)
then
    // Povišen oprez / kašnjenje ako nije kritično
end

rule "Aggregation - Takeoff Forbidden due to combined CRITICAL hazards"
salience 500
when
    $f : Flight($fn : flightNumber)
    RunwayCritical(flightNumber == $fn) 
    SurfacesContaminated(flightNumber == $fn)
then
    TakeoffForbidden fact = new TakeoffForbidden();
    fact.setFlightNumber($fn);
    insert(fact);
end

rule "Aggregation - Takeoff Forbidden due to critical runway state"
salience 500
when
    $f : Flight($fn : flightNumber)
    RunwayCritical(flightNumber == $fn) // Samo ako je pista kritična (rwycc <= 1)
then
    TakeoffForbidden fact = new TakeoffForbidden();
    fact.setFlightNumber($fn);
    insert(fact);
end